### ISSUE TITLE
MySQLの文字コード設定

### ISSUE THREAD

**Issue by Soki-Oda** [tokyodigitalhistory/QAs#1]
## 質問内容
- MySQLでテーブルからデータを取得したときに文字化けします。
- create database のときにはdefault character set をutf8にしています。

## 調査内容とその理解
1.  https://www.dbonline.jp/mysql/myini/index3.html
```
サーバ側とクライアント側の文字コードを一致させておけば、（中略）文字化けなどを心配する必要はありません。
```
2.  https://www.dbonline.jp/mysql/install/index3.html
```
MySQLに関する設定は設定ファイルに記述します。設定ファイルは「my.ini」ファイル（中略）が使用されます。
```
## 調査で得られた情報の理解
- サーバ側・クライアント側双方の文字コードをutf8にすればよい。
- my.iniを書き換える必要がある。たぶん。

## 調査の結果、残った疑問や懸念
```
mysql> show variables like 'char%'; 
```
で調べると、
```
character_set_client     | cp932
（中略）
character_set_server     | utf8mb4 
```
となっているので、これを2つともutf8にしたい。

- my.iniを見ることはできたが、どう書き換えればよいかわからない。

##関連情報
- https://www.dbonline.jp/mysql/
このサイトでMySQLの基礎的なことは勉強できました。ここに載っていない使い方がどのぐらいあるのかは知りません。

- https://oss-db.jp/dojo/dojo_info_04
正規化についてはここをみました（佐治さんに教えてもらいました）。

## 添付ファイル
- [my.ini.txt](https://github.com/tokyodigitalhistory/QAs/files/2920338/my.ini.txt)
- https://docs.google.com/spreadsheets/d/1b3ffp-J6JvCqgkHWhxjry7Tw1boByVWSFS-aHvrAxMg/edit#gid=0

## その他
- 添付ファイルにある表を使ってデータベースを作っています。urk_idとempfをprimary keyにして正規化したつもりが、テーブルを2つ作って内部結合してみたところで、全然（第2）正規化ができていないことに気づきました。empfのカラムを修正するのが大変そうだったので、先に文字コードの問題を解決してしまいたいと思って質問しました。
- そもそもこの表がデータベース化に適したものかよくわかっていません。何がしたいのかは改めて説明したいと思いますが、エクセルで済むことなのかもしれません。しかしMySQLがけっこうおもしろかったので試しにDB化しています。

**Comment by ppppn** [comment]
みてます

**Comment by ppppn** [comment]
@Soki-Oda 

`mysql 文字コード`でググったところ、↓のようなページが出ましたが、例えばこちらはご覧になっているでしょうか。

https://qiita.com/YusukeHigaki/items/2cab311d2a559a543e3a
```
デフォルトをきちんと設定しておく
そもそも作成したDBの文字コードが意図しない設定になっていたら、デフォルトの設定が間違っている可能性が高いので、再度同じ問題を起こさないためにも、設定見直し→DBをdrop→DBをcreateという順番で直しに行きます。
[...]
utf8に設定する
変更するには設定ファイルに書き込む。

/etc/my.cnf
[mysqld]
...
character-set-server=utf8 #mysqldセクションの末尾に追加

[client]
default-character-set=utf8 #clientセクションを追加
再起動。

/etc/init.d/mysqld restart
文字コードの確認をする
再度データベースを作りなおしたらきちんと文字コードが設定されているか確認します。
```

大事なのは、 **設定見直し→DBをdrop→DBをcreate** や **再起動。**、**再度データベースを作りなおしたら** という部分かと思われますが、このあたりはチェックいただいていますでしょうか。

そもそも、ここの設定って何を意味するのー?という点については http://gihyo.jp/dev/serial/01/mysql-road-construction-news/0065

公式マニュアルだとこの辺でしょうか。
https://dev.mysql.com/doc/refman/5.6/ja/charset-configuration.html

あと、現時点で関係あるかはわかりませんが、お使いになっているOSやアプリケーションのバージョンも記載いただけると助かります(OSやバージョンによって挙動が大きく変わる場合がある)。
これはテンプレートの問題ですね。スキを見て直します。

そして、my.iniを見た限りですが、もしかして、MySQL 5.1を使ってます?
最新版は8.0で、1つ前でも5.7で、おそらく、5.1は2019年現在は化石です……。

**Comment by Soki-Oda** [comment]
@ppppn 

回答ありがとうございました。教えていただいたQiitaのページはみていませんでした。
また、OSはWindows10で、MySQLは8.0を使っています。
my.iniを書き換えようといろいろ調べているうちにどこかのページで5.1時代のテンプレートをみつけて、それをコピペしてしまったのだと思います。しかし参照したページがわからなくなってしまいました。

どうにかしようと思いましたが、新しいissueで質問したようにMySQLに接続できなくなっています。
もともとのmy.iniの記述を残しておらず復元できないので、再インストールしたほうがいいでしょうか？

**Comment by ppppn** [comment]
再インストールしていただくのが良いかと思います。
my.iniとかはサーバーの挙動を設定するファイルなので、編集される際は、バックアップを取ってください。

gitの管理下においてもいいですね。
例えば、Linuxの場合ですがetckeeperというツールで、VCS管理下に置くことができます。

**Comment by ppppn** [comment]
This issue is not update for long time. I close this issue.
If you have question, please reopen this issue.
