### ISSUE TITLE
コマンドプロンプトからMySQLに接続できない

### ISSUE THREAD

**Issue by Soki-Oda** [tokyodigitalhistory/QAs#2]
@ppppn

回答ありがとうございました。昨日回答をいただいてからMySQLに接続しようとしたところ、できなくなってしまいました。以下に試した対処法を書くので、他に対処法があれば教えていただきたいです。

いつもコマンドプロンプトからMySQLに接続しています。「管理者として実行」して接続しようとすると、次のようなエラーが出ます。
```
C:\WINDOWS\system32>mysql -u root -p
Enter password: *********
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (10061)
```
PATHが通っていることは確認しました。エラーメッセージでググって、まずはここをみました。
http://ingwer-design.com/blog/mysql/mysql.html
```
通常の対処法
［スタート］→［コントロールパネル］→［管理ツール］→［サービス］を選び、「MySQL」を選択した上で「サービスの開始」リンクをクリックします。サービスを起動させたら、もう一度MySQLクライアントプログラムの起動コマンドを試してみましょう。
```

この通りやってみると。
```
ローカルコンピュータ上のMySQLサービスは起動して停止しました。サービスの中には、ほかのサービスやプログラムで使用されていない場合は自動的に停止するものがあります。
```
というエラーが出ました。

このエラーでググって、
https://teratail.com/questions/109690
```
参考URL
プロセスが残ってるかもしれませんね。確認してみてください。
```
という回答をみて、このページに行って、
http://mysql.javarou.com/dat/000823.html
```
Windows の場合、Ctrl + Shift + Del の３つのキーを同時に押した後、タスクマネージャーの起動を選択すると、次のような小画面で mysqld のプロセスを確認できます。
```
この通りやってみましたが、プロセスは残っていませんでした。
どうすればよいでしょうか。

**Comment by ppppn** [comment]
何らかの事情でMySQLデーモンが動いてないと思われます。
アンインストール→再インストールができるのであれば、そのように対応いただくのがよろしいかと思います。

**Comment by ppppn** [comment]
This issue is not update for long time. I close this issue.
If you have question, please reopen this issue.
